import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cn } from '@/lib/utils'
import Providers from '@/context/Providers'
import ActiveSectionContextProvider from '@/context/ActiveSection'
import Image from 'next/image'
import Navbar from '@/components/Navbar'
import Directions from '@/components/Directions'
import MobileMenu from '@/components/MobileMenu'
import Footer from '@/components/home/Footer'
import Contact from '@/components/home/Contact'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Climb X',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"
    >
      <body
        className={cn('bg-white text-slate-900 relative antialiased min-h-screen dark:bg-slate-900', inter.className)}
      >
        <Providers>
          <ActiveSectionContextProvider>
            <Navbar />
            <main>{children}</main>
            <MobileMenu />
            <Contact />
            <Footer />
          </ActiveSectionContextProvider>
        </Providers>
      </body>
    </html>
  )
}
